### ISSUE TITLE
Page stuck at 'Converting' but response came

### ISSUE THREAD

**Issue by PatiDev** [JamieMagee/reddit2kindle#1]
Hello,
Sometimes when I use your site and click 'Convert' the page is stuck at 'Converting'.
I can see in the 'Network' tab in Chrome that there was some POST for /subreddit and the response came with an error: 400 Bad Request CSRF token missing or incorrect
I don't know why the token is missing, I believe the token is passed automatically so there is some issue here. You should also show some info that the request went wrong and to reload the page or something.

![r2k](https://cloud.githubusercontent.com/assets/23015528/20708933/9fefe76c-b632-11e6-891a-8681539772e0.png)

**Comment by JamieMagee** [comment]
My best guess is that if you have the page open for a long time, the instance on Azure spins down after 5 minutes of inactivity, and so the CSRF token is considered invalid when a new instance spins up.

I'll add some info, instead of just getting it stuck at "Converting".

**Comment by JamieMagee** [comment]
I've decided to show an error message instead of increasing the Azure service plan.
