### ISSUE TITLE
Padding issue on Kindle Oasis

### ISSUE THREAD

**Issue by Gunni** [JamieMagee/reddit2kindle#32]
Hey,

I posted [this twitter post](https://twitter.com/Jamie_Magee/status/1300358688079777792). I'm bad at twittering so maybe this is nicer to use.

Anyway, [your patch](https://github.com/JamieMagee/reddit2kindle/commit/2356733a3a8a030f7f027bf69f476cc4607be4ba) did not solve my problem, it looks unchanged.

I sent [this post](https://www.reddit.com/r/HFY/comments/ikjpar/the_humans_do_not_have_three_brains_part_8/) to my Kindle Oasis, this is what it looks like:

![20200901_202948](https://user-images.githubusercontent.com/358099/91903079-26e2ce80-ec92-11ea-83fe-60a99093e7f3.jpg)

**Comment by JamieMagee** [comment]
Yeah, this is probably the easiest way to work on this.

Right now I'm mostly guessing at a fix. I only have access to a Kindle Paperwhite or the Kindle Android app, and both of those appear correctly.

**Comment by Gunni** [comment]
If you want, you can send some test lorem-ipsums to my kindle with different margins to find a good value.

**Comment by JamieMagee** [comment]
Sure, can you send me your kindle address as a Twitter DM?

**Comment by Gunni** [comment]
> Sure, can you send me your kindle address as a Twitter DM?

Twitter says `@Jamie_Magee can’t be messaged`

**Comment by JamieMagee** [comment]
@Gunni I've completely rewritten reddit2kindle using a more modern stack. Can you let me know if the display is any better on your Kindle Oasis?

**Comment by Gunni** [comment]
Hi, just to report, i tried one post, looks great, except for one bug i'll report seperately.
