### ISSUE TITLE
First comment blends into post

### ISSUE THREAD

**Issue by Gunni** [JamieMagee/reddit2kindle#38]
With the new system i tested yesterday, i noticed that the first comment was just appended to the post, there was no indication the post ended and comments started.

I'll post a screenshot when i get time.

**Comment by JamieMagee** [comment]
Thanks for testing it out.

Was the issue with an individual post, or a subreddit? A screenshot/photo will really help. Thanks!

**Comment by Gunni** [comment]
Example post: https://www.reddit.com/r/HFY/comments/mcp1wd/they_were_thought_to_be_weak/

Screenshot:
![screenshot_2021_04_28T02_04_28+0000](https://user-images.githubusercontent.com/358099/116335312-31744a00-a7c6-11eb-9add-02ec87a5d96b.png)

As can be seen on the screenshot, the comment is indented a bit, but on the kindle, when reading, it is barely visible at all.

A picture:
![PXL_20210428_020801346](https://user-images.githubusercontent.com/358099/116335870-15bd7380-a7c7-11eb-98b8-70c1162cc753.jpg)

**Comment by JamieMagee** [comment]
Thanks for the screenshots. I'm thinking of making the border around the post text more obvious, like a thicker solid or dotted line. Would that work for you?

**Comment by Gunni** [comment]
Sounds like a good idea, feel free to send me a document with the change to check. Or just let me know after you applied that change.

**Comment by JamieMagee** [comment]
I added a border at the bottom of the post's text and made the colour of the blockquote a bit darker as well.

Here's how it renders on my PC:
![image](https://user-images.githubusercontent.com/1358764/116796512-dd04ef00-aa91-11eb-9555-2d57695361d6.png)

**Comment by Gunni** [comment]
Looks great!

![3](https://user-images.githubusercontent.com/358099/116806685-43375380-ab1e-11eb-8cb6-f5f3db66ec80.png)
